import type { Metadata } from 'next'
import 'tailwindcss/tailwind.css';
import ClientProvider from "@/app/components/ClientProvider";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-blackBackground">
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  )
}
